using System.Text.Json.Serialization;
using MiniOcr.Models;

namespace MiniOcr;

[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    WriteIndented = false)]
[JsonSerializable(typeof(OcrDebugRequest))]
[JsonSerializable(typeof(OcrTextDebugResponse))]
[JsonSerializable(typeof(OcrTextDebugPage))]
[JsonSerializable(typeof(List<OcrTextDebugPage>))]
[JsonSerializable(typeof(OcrResponse))]
[JsonSerializable(typeof(OcrPageResult))]
[JsonSerializable(typeof(OcrTimings))]
[JsonSerializable(typeof(OcrEntities))]
[JsonSerializable(typeof(EntityHit))]
[JsonSerializable(typeof(HealthResponse))]
[JsonSerializable(typeof(List<OcrPageResult>))]
[JsonSerializable(typeof(List<EntityHit>))]
[JsonSerializable(typeof(AppConfigFile))]
[JsonSerializable(typeof(LlmFileConfig))]
[JsonSerializable(typeof(OcrFileConfig))]
[JsonSerializable(typeof(ChatCompletionRequest))]
[JsonSerializable(typeof(ChatResponseFormat))]
[JsonSerializable(typeof(ChatCompletionResponse))]
[JsonSerializable(typeof(ChatChoice))]
[JsonSerializable(typeof(ChatMessage))]
[JsonSerializable(typeof(VisionChatCompletionRequest))]
[JsonSerializable(typeof(VisionChatMessage))]
[JsonSerializable(typeof(VisionContentPart))]
[JsonSerializable(typeof(VisionImageUrl))]
[JsonSerializable(typeof(ThinkingOption))]
[JsonSerializable(typeof(List<VisionChatMessage>))]
[JsonSerializable(typeof(List<VisionContentPart>))]
[JsonSerializable(typeof(LlmEntityPayload))]
[JsonSerializable(typeof(LlmVisionOcrPayload))]
[JsonSerializable(typeof(List<ChatMessage>))]
[JsonSerializable(typeof(List<ChatChoice>))]
[JsonSerializable(typeof(List<string>))]
[JsonSerializable(typeof(ChallengeRequest))]
[JsonSerializable(typeof(ChallengeFileRef))]
[JsonSerializable(typeof(ChallengeAckResponse))]
[JsonSerializable(typeof(ChallengeCallbackBody))]
[JsonSerializable(typeof(ChallengeFileResult))]
[JsonSerializable(typeof(ChallengePageResult))]
[JsonSerializable(typeof(ChallengeRule))]
[JsonSerializable(typeof(ChallengeRuleItem))]
[JsonSerializable(typeof(List<ChallengeFileResult>))]
[JsonSerializable(typeof(List<ChallengePageResult>))]
[JsonSerializable(typeof(List<ChallengeRule>))]
[JsonSerializable(typeof(List<ChallengeRuleItem>))]
[JsonSerializable(typeof(List<ChallengeFileRef>))]
[JsonSerializable(typeof(ClusterFileConfig))]
[JsonSerializable(typeof(ClusterWorkerFileConfig))]
[JsonSerializable(typeof(List<ClusterWorkerFileConfig>))]
[JsonSerializable(typeof(ClusterHealthInfo))]
[JsonSerializable(typeof(ClusterNodeHealth))]
[JsonSerializable(typeof(List<ClusterNodeHealth>))]
[JsonSerializable(typeof(ClusterLastJobHealth))]
[JsonSerializable(typeof(ClusterNodePages))]
[JsonSerializable(typeof(List<ClusterNodePages>))]
[JsonSerializable(typeof(ClusterRegisterRequest))]
[JsonSerializable(typeof(ClusterRegisterResponse))]
[JsonSerializable(typeof(ClusterHeartbeatRequest))]
[JsonSerializable(typeof(ClusterInfoResponse))]
[JsonSerializable(typeof(ClusterNotifyRequest))]
[JsonSerializable(typeof(ClusterDispatchRequest))]
[JsonSerializable(typeof(ClusterDispatchResponse))]
[JsonSerializable(typeof(ClusterJoinRequest))]
[JsonSerializable(typeof(ClusterClaimRequest))]
[JsonSerializable(typeof(ClusterClaimResponse))]
[JsonSerializable(typeof(ClusterResultRequest))]
[JsonSerializable(typeof(ClusterFailRequest))]
[JsonSerializable(typeof(ClusterAck))]
[JsonSerializable(typeof(ClusterNerClaimRequest))]
[JsonSerializable(typeof(ClusterNerClaimResponse))]
[JsonSerializable(typeof(ClusterNerPageText))]
[JsonSerializable(typeof(List<ClusterNerPageText>))]
[JsonSerializable(typeof(ClusterNerEntityHit))]
[JsonSerializable(typeof(List<ClusterNerEntityHit>))]
[JsonSerializable(typeof(ClusterNerResultRequest))]
[JsonSerializable(typeof(NacosInstanceListResponse))]
[JsonSerializable(typeof(NacosInstance))]
[JsonSerializable(typeof(List<NacosInstance>))]
[JsonSerializable(typeof(NacosLoginResponse))]
[JsonSerializable(typeof(Dictionary<string, string>))]
[JsonSerializable(typeof(NacosFileConfig))]
[JsonSerializable(typeof(List<int>))]
public partial class AppJsonContext : JsonSerializerContext;
