using System.Text.Json.Serialization;
using MiniOcr.Models;

namespace MiniOcr;

[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    WriteIndented = false)]
[JsonSerializable(typeof(OcrDebugRequest))]
[JsonSerializable(typeof(OcrResponse))]
[JsonSerializable(typeof(OcrPageResult))]
[JsonSerializable(typeof(OcrTimings))]
[JsonSerializable(typeof(OcrEntities))]
[JsonSerializable(typeof(EntityHit))]
[JsonSerializable(typeof(HealthResponse))]
[JsonSerializable(typeof(List<OcrPageResult>))]
[JsonSerializable(typeof(List<EntityHit>))]
[JsonSerializable(typeof(AppConfigFile))]
[JsonSerializable(typeof(LlmFileConfig))]
[JsonSerializable(typeof(OcrFileConfig))]
[JsonSerializable(typeof(HunyuanFileConfig))]
[JsonSerializable(typeof(HunyuanChatCompletionRequest))]
[JsonSerializable(typeof(HunyuanChatMessage))]
[JsonSerializable(typeof(HunyuanContentPart))]
[JsonSerializable(typeof(HunyuanImageUrl))]
[JsonSerializable(typeof(List<HunyuanChatMessage>))]
[JsonSerializable(typeof(List<HunyuanContentPart>))]
[JsonSerializable(typeof(ChatCompletionRequest))]
[JsonSerializable(typeof(ChatCompletionResponse))]
[JsonSerializable(typeof(ChatChoice))]
[JsonSerializable(typeof(ChatMessage))]
[JsonSerializable(typeof(VisionChatCompletionRequest))]
[JsonSerializable(typeof(VisionChatMessage))]
[JsonSerializable(typeof(VisionContentPart))]
[JsonSerializable(typeof(VisionImageUrl))]
[JsonSerializable(typeof(ThinkingOption))]
[JsonSerializable(typeof(List<VisionChatMessage>))]
[JsonSerializable(typeof(List<VisionContentPart>))]
[JsonSerializable(typeof(LlmEntityPayload))]
[JsonSerializable(typeof(LlmVisionOcrPayload))]
[JsonSerializable(typeof(List<ChatMessage>))]
[JsonSerializable(typeof(List<ChatChoice>))]
[JsonSerializable(typeof(List<string>))]
[JsonSerializable(typeof(ChallengeRequest))]
[JsonSerializable(typeof(ChallengeFileRef))]
[JsonSerializable(typeof(ChallengeAckResponse))]
[JsonSerializable(typeof(ChallengeCallbackBody))]
[JsonSerializable(typeof(ChallengeFileResult))]
[JsonSerializable(typeof(ChallengePageResult))]
[JsonSerializable(typeof(ChallengeRule))]
[JsonSerializable(typeof(ChallengeRuleItem))]
[JsonSerializable(typeof(List<ChallengeFileResult>))]
[JsonSerializable(typeof(List<ChallengePageResult>))]
[JsonSerializable(typeof(List<ChallengeRule>))]
[JsonSerializable(typeof(List<ChallengeRuleItem>))]
[JsonSerializable(typeof(List<ChallengeFileRef>))]
internal partial class AppJsonContext : JsonSerializerContext;
