<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PublishAot>false</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
    <IsPackable>false</IsPackable>
    <NoWarn>$(NoWarn);CA1416;IL2026;IL3050</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../external/SimdPaddleOCR/src/Sdcb.SimdPaddleOCR/Sdcb.SimdPaddleOCR.csproj" />
    <ProjectReference Include="../../external/SimdPaddleOCR/src/models/Sdcb.SimdPaddleOCR.Models.ChineseV6Tiny/Sdcb.SimdPaddleOCR.Models.ChineseV6Tiny.csproj" />
    <ProjectReference Include="../../external/PDFtoImage/src/PDFtoImage/PDFtoImage.csproj" />
    <TrimmerRootAssembly Include="Sdcb.SimdPaddleOCR" />
    <TrimmerRootAssembly Include="Sdcb.SimdPaddleOCR.Models.ChineseV6Tiny" />
    <TrimmerRootAssembly Include="PDFtoImage" />
    <TrimmerRootAssembly Include="SkiaSharp" />
  </ItemGroup>
</Project>
